"""Add security_answer to user

Revision ID: 9b36cd81dad4
Revises: ce7176890613
Create Date: 2026-07-04 22:57:58.470012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b36cd81dad4'
down_revision = 'ce7176890613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('security_answer', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('security_answer')

    # ### end Alembic commands ###
